### ISSUE TITLE
desktop-installer completes but FreeBSD won't launch a window manager (KDE, Lumina etc) 

### ISSUE THREAD

**Issue by almostunix** [outpaddling/desktop-installer#12] opened 2021-05-24 20:13 UTC
Hello, 

I am new to git, so please forgive me if I am "doing this wrong". I have attempted to use the desktop-installer pkg both on a raspberry PI4 and on a Virtual Machine on my Mac (via parallels) and unfortunately neither one gets me into a desktop as expected. 

The setup seems to complete satisfactorily but upon reboot at the end it routes back to the command line rather than bringing up a GUI login. 

Any help is greatly appreciated. I have tried reinstalling several times (along with recreating the VM) 
Prior to running desktop-installer I updated and upgraded packages, FreeBSD otherwise seems to be running quite well. 

I am currently using FreeBSD 13 Release. Parallels 15 on a MacAir with 16GB Ram (last of the intel processors) and a thunderbolt drive is hosting the VM. 

I also attempted to run this on a Raspberry Pi 4 with a similar result. 

Thanks!

**Comment by outpaddling** [comment] 2021-05-24 21:30
Does the GUI work during setup if you answer 'y' to testing X11?

Unfortunately, I do not have access to a Rasberry Pi or Parallels for testing.  I have tested under VirtualBox on a Mac and that works well.

**Comment by almostunix** [comment] 2021-05-25 20:00
> Does the GUI work during setup if you answer 'y' to testing X11?
> 
> Unfortunately, I do not have access to a Rasberry Pi or Parallels for testing. I have tested under VirtualBox on a Mac and that works well.

>Just tried it on VM-Ware Fusion12 (VM Ware, I run ESXi so figured it would be a natural jump.) same issue as the other platforms. 

>To answer you question, I have tried answering y to testing X11 and no dice. I am including a screenshot of the error received when I run "startx" manually from the cmd line on the most recent attempt on a VMware VM. it was similar if not identical on the other platforms. (This most recent install was trying to run Lumina.) 

One question I do have is around 3d acceleration. that has been enabled on each setup, is that potentially an issue?

I can give Virtualbox a try here at some point (there was a note saying it didn't play nice so was staying away from it.) 


<img width="972" alt="Screen Shot 2021-05-25 at 3 55 59 PM" src="https://user-images.githubusercontent.com/84742533/119560442-f6881680-bd71-11eb-932a-2dad956d6b25.png">

**Comment by outpaddling** [comment] 2021-05-25 20:39
Definitely a video driver issue.  There are additional drivers to try.  Run 'pkg search xf86-video' for a list.  This is more likely to help on the Rasberry Pi.  I don't think you should need them under Parallels or VMWare, but I could be wrong.

Can you share your full set of responses to desktop-installer?  Most of them are shown by
`grep desktop /root/.config/auto-ask-responses`
though a few questions don't use auto-ask and therefore are not recorded.
Also please share any VM settings that are not default.

If you're referring to the note about Lumina under VirtualBox, the issues are only cosmetic:
[https://github.com/lumina-desktop/lumina/issues/536#issuecomment-847198390](https://github.com/lumina-desktop/lumina/issues/536#issuecomment-847198390)

Thanks...

**Comment by outpaddling** [comment] 2021-05-26 00:44
I installed the Parallels 14-day free trial and was able to reproduce the issue.  I found some good info here: [https://forums.freebsd.org/threads/parallels-compatible-display-driver.73378/](https://forums.freebsd.org/threads/parallels-compatible-display-driver.73378/)

Just added an enhancement to the WIP version of desktop-installer that detects when running under Parallels and adds an xorg.conf fragment to force use of the SCFB driver.  `Xorg -configure` selected modesetting, which seems odd to me.  You can try out the WIP collection here: [https://github.com/outpaddling/freebsd-ports-wip](https://github.com/outpaddling/freebsd-ports-wip)
Or for a quick fix, add the following to /etc/X11/xorg.conf.d/10-parallels-scfb.conf:
```
Section "Device"
        ### Force SCFB driver for Parallels 15+
        Identifier  "Card0"
        Driver      "scfb"
        BusID       "PCI:1:0:0"
EndSection
```
There's also some info on the forum thread about setting higher resolutions, but you can probably also control this with xorg.conf fragments in the Screen section.

**Comment by auerlab** [comment] 2021-05-26 13:18
From my perspective, VirtualBox looks like a better platform for hosting FreeBSD VMs, since FreeBSD can run the guest additions for mouse integration, screen resizing, etc.
I'm not seeing much info around on Raspberry Pi graphics.  I'm guessing the GPU capabilities vary widely.  I would think VESA or SCFB would work in some cases, but I'll have to rely on others to provide info.  Please let me know if you figure out the proper settings for your board.  If there's a reasonable way to support this in desktop-installer, I will.

**Comment by outpaddling** [comment] 2021-05-26 14:04
"Auerlab" is me, BTW.  Forgot I had signed in under that name.

**Comment by almostunix** [comment] 2021-05-26 14:51
Let me read through the thread you sent and check a couple of the video driver loads/edits. Thank you for checking into this. I will respond in a little bit with the info you requested and whether the edits worked on my machine.

**Comment by almostunix** [comment] 2021-05-26 22:43
> "Auerlab" is me, BTW. Forgot I had signed in under that name.

>Hi there, fantastic advice on the quick fix. I can look further into it later but I just booted up KDE Plasma (on FreeBSD) from the previous desktop-installer setup, using the edit to the scfb.conf you mentioned. 

>Thanks for the help. Makes installing FreeBSD very quick. (Anecdotally, Parallels seems to run much faster on my Mac than VirtualBox for FreeBSD, I can measure at some point to see if that is perception or actual, Fusion 12 seemed to run the fastest, (again anecdotally) and is free for non-commercial use (free license available via VMWare's website). I will have to test the same fix there, but assume it would work, as it sounds like the video driver was the issue.

**Comment by outpaddling** [comment] 2021-05-27 14:05
I just moved the VM guest detection from desktop-installer to auto-gpu-setup (part of sysutils/auto-admin) and added support for VMWare.  VMWare works with the same SCFB hack as Parallels.
The changes are available in WIP: [https://github.com/outpaddling/freebsd-ports-wip](https://github.com/outpaddling/freebsd-ports-wip).  To try them, run `auto-freebsd-wip-checkout git` followed by `wip-reinstall-port auto-admin` followed by `wip-reinstall-port desktop-installer`.
I'll commit these changes to ports-proper following a brief testing period.

**Comment by outpaddling** [comment] 2021-05-28 16:24
Actually it looks like installing xf86-video-vmware is a better option than forcing XCFB for VMWare guests.  The vmware driver provides a variety of screen resolutions.  I just updated the WIP packages.
I'm not seeing a better option than SCFB for Parallels right now, but please chime in if you know of one.

**Comment by outpaddling** [comment] 2021-05-29 00:42
Committed auto-admin 9.7.4 and desktop-installer 0.7.3 with support for Parallels and VMWare.
Let me know if you have any ideas for Raspberry Pi.

**Comment by outpaddling** [comment] 2021-06-05 13:26
Feel free to reopen if you have any additional comments.

**Closed by outpaddling** 2021-06-05 13:26 UTC
