### ISSUE TITLE
desktop installer errors

### ISSUE THREAD

**Issue by halfagascan** [outpaddling/desktop-installer#24] opened 2022-01-30 18:19 UTC
clean install of freebsd 
13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021
install desktop-installer according to your instructions, no ports tree
errors:
Press return to continue...
Installing src tree...
/usr/local/sbin/auto-install-base-components: 13.0-RELEASE: not found
Fetching ftp://ftp.freebsd.org/pub/FreeBSD/snapshots/amd64/13.0-RELEASE/src.txz...
fetch: ftp://ftp.freebsd.org/pub/FreeBSD/snapshots/amd64/13.0-RELEASE/src.txz: File unavailable (e.g., file not found, no access)

**Comment by outpaddling** [comment] 2022-01-30 20:25
What version of auto-admin is installed?  This issue was recently fixed and should not be happening with 0.7.9.

**Comment by outpaddling** [comment] 2022-01-31 16:58
Slight delay in getting the quarterly package fixed.  The problem is in /usr/local/sbin/auto-install-base-components.  If you apply the following fix, it should work:

```
-           if `uname -r` | fgrep -q RELEASE; then
+           if uname -r | fgrep -q RELEASE; then

```

**Comment by outpaddling** [comment] 2022-02-02 18:18
Fix has been committed to 2022Q1 ports.  The binary package should be updated within a few days (at least for amd64 and probably aarch64, not sure about 2nd tier platforms).
Thanks for the report!

**Closed by outpaddling** 2022-02-02 18:18 UTC

**Comment by outpaddling** [comment] 2022-02-12 15:01
It looks like package builds are delayed due to build cluster upgrades, so this fix hasn't made it into the binary packages yet.
For now, you can work around it by installing the WIP port before running desktop-installer:

```
pkg install auto-admin
auto-freebsd-wip-checkout
wip-reinstall-port auto-admin
wip-reinstall-port desktop-installer
desktop-installer
```

Apologies for the broken quarterly package.  I failed to test fully before the Jan 1 branch.  This is unusual, as I generally give auto-admin and desktop-installer a lot of attention to prevent regressions.

**Comment by outpaddling** [comment] 2022-02-17 23:31
Build farm has caught up and everything is working out-of-the-box again with binary packages for both quarterly and latest selections.  Thanks again for the heads-up and I apologize for the mishap.  Making desktop-installer trouble-free is my highest priority and I have updated my commit procedures to prevent a repeat of this error.

**Comment by grahamperrin** [comment] 2022-03-18 08:07
@halfagascan comparable to the _closure_ here in GitHub, you can (should) mark your topic as _Solved_ in FreeBSD Forums. 

<https://forums.freebsd.org/posts/554378> "You can [add the Solved prefix](https://forums.freebsd.org/threads/encouraging-use-of-the-solved-prefix.82253/) …"
