### ISSUE TITLE
desktop-installer does not work with zfs root filesystem

### ISSUE THREAD

**Issue by tbalbers** [outpaddling/desktop-installer#4] opened 2021-02-25 10:04 UTC
Hiya,
When trying to use desktop-install on a newly installed FreeBSD 12.2, I get an error if /usr/ports are added during install and I chose to use the 2021Q1 ports. The script tries to mv /usr/ports /usr/ports.0 bu fails and exits with the messages: Operation not supported.
This is because /usr/ports is a separate ZFS filesystem, so: 'zfs destroy zroot/usr/ports' removes the /usr/ports directory and running desktop-installer again the just downloads the release of /usr/ports that it wants.

Maybe there should be some kind of automagic resolution to this or at least an information about what to do.

**Comment by outpaddling** [comment] 2021-02-25 21:27
Thanks for the bug report!
This is actually not a desktop-installer bug.  The problem is in sysutils/auto-admin, script auto-check-ports-branch.  An update will be committed to -latest shortly.
You can test the fix immediately regardless of whether you use quarterly or latest by installing from my work-in-progress collection:

```
auto-freebsd-wip-checkout git
wip-reinstall-port auto-admin
wip-reinstall-port desktop-installer
```

**Closed by outpaddling** 2021-02-25 21:27 UTC
